version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    ports:
      - 4000:4000
    volumes:
      - ../:/usr/src/app
    tty: true
    networks:
      - kube-guide

networks:
  kube-guide:
    driver: bridge